name: Deploy to EC2

on:
  push:
    branches:
      - main # mainブランチにプッシュされた時に実行されます

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH/rsync
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }} # 「.」に修正しました
          username: ${{ secrets.EC2_USER }} # 「.」に修正しました
          key: ${{ secrets.EC2_SSH_KEY }} # 「.」に修正しました
          source: "."
          target: "/var/www/html"
